services:
  loadbalancer:
    build:
      context: .
      dockerfile: load_balancer/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - SERVER_PORT=5000
    networks:
      app-network:
        aliases:
          - loadbalancer
    depends_on:
      server1:
        condition: service_healthy
      server2:
        condition: service_healthy
      server3:
        condition: service_healthy

  server1:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - SERVER_ID=1
      - PORT=5000
    hostname: server1
    container_name: server1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/heartbeat"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      app-network:
        aliases:
          - server1

  server2:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - SERVER_ID=2
      - PORT=5000
    hostname: server2
    container_name: server2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/heartbeat"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      app-network:
        aliases:
          - server2

  server3:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - SERVER_ID=3
      - PORT=5000
    hostname: server3
    container_name: server3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/heartbeat"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      app-network:
        aliases:
          - server3

networks:
  app-network:
    driver: bridge
